### ISSUE TITLE
Stuck on a block 

### ISSUE THREAD

**Issue by Jr030296** [MorpheusWallet/beta#24]
My wallet is stuck on block 2155784 and I cannot get it to update!

**Comment by MorpheusAdministrator** [comment]
Hey @Jr030296 - Lots of nodes went down and neon-wallet database server which we and other wallet use were also down yesterday.

**Comment by Jr030296** [comment]
Thanks for the reply! I'll admit I was a little sweaty, I had just moved a
good portion of my block chain assets to the Morpheus wallet.  But all
appears to be working well now.
