### ISSUE TITLE
How do we had an Hashscript address into the Wallet?

### ISSUE THREAD

**Issue by Zargouf** [MorpheusWallet/beta#25]
I've completed an ICO with my NEO Address on Morpheus Wallet and my NEP-5 Token from Effect.ai are not showing in it. The Effect.ai group send a video about how to add an Hashscript into the original NEO wallet (I think it's the original) but not with others. But they do say that you can just add their Hashscript into any other wallets that support NEO, GAS and NEP-5 Tokens.

So, i'm wondering how can i make them appear in my wallet. 

ALSO, you guys have miss spelled Effect.ai... haha you wrote ''Effer.ai'' so disappointing (xD)
Hoping to have an awnser really soon! I'm exited about this Project! Later!

SPA

**Comment by MorpheusAdministrator** [comment]
Hey thanks for the feedback, ability to manually add script hashes are coming in a future update. Till then we'll try to keep up and eerrr, spell them correctly 😃

**Comment by MorpheusAdministrator** [comment]
Hmmm, how have you lost your assets??
Your tokens are on the blockchain, you can access via any NEO wallet you prefer using your private key and encrypted key and password. 
We added Effect.ai script hash in 0.0.57. You can try with that version

**Comment by Zargouf** [comment]
Thanks, it's all good!
Didn't known that you could use a different software and enter a private key and encrypted key passwords from an other wallet :O 
I always thought that these key were only for one unique software wallet.

Thx for the tip!
