### ISSUE TITLE
Cannot send LTC from LTC wallet

### ISSUE THREAD

**Issue by CaptCrypto** [MorpheusWallet/beta#26]
I created a new wallet inside the Morpheus app on Mac (using v0.0.56), send 1 LTC as a test from Binance. At first, the amount wasn't even loading, upgraded to v.0.0.57 and now the amount can be seen. 

The problem lies when you try to send some LTC to another address, the app just keeps "processing" indefinitely. From the blockchain explorer it can be seen that no amounts are spent, UTXO remains the same. 

<img width="1055" alt="screen shot 2018-04-28 at 22 27 15" src="https://user-images.githubusercontent.com/31131978/39400205-a006df7e-4b34-11e8-9a68-6c81bdf0b383.png">

**Comment by MorpheusAdministrator** [comment]
Hey @CaptCrypto - were you able to send you funds. I just tested and was able to process a transaction. Our service provider may have been having issues at the time you were trying. Please let me know.

![screen shot 2018-05-01 at 1 36 23 pm](https://user-images.githubusercontent.com/13420186/39484728-ad3fbe06-4d44-11e8-8c29-2e47e88254b7.png)

**Comment by CaptCrypto** [comment]
Hello @MorpheusAdministrator - I haven't tested it, moved all my funds away from Morpheus using Electrum since that incident.

**Comment by MorpheusAdministrator** [comment]
Thanks for the feedback Cap! Glad you were able to access your funds.
