### ISSUE TITLE
Hangs when saving a newly created NEO address on dev build

### ISSUE THREAD

**Issue by lucidsif** [MorpheusWallet/beta#4]
Error message (screenshot attached): "Uncaught (in promise) TypeError: Cannot read property 'dataPath' of undefined at Object.exports.set..."

To reproduce:
1. Click on 'Create a new NEO Address' on the bottom menu.
2. Enter a valid password on both password fields and click on the 'Create Address' button.
3. Wait for wallet keys to be generated and the 'New NEO Address Created' screen to load .
4. Enter any valid string in 'Name Your Address' input field for e.g. 'mywallet1'.
5. Click on the 'Save Address and Login' button.

![Uploading image.png…]()

**Comment by MorpheusAdministrator** [comment]
thanks will look into it

**Comment by MorpheusAdministrator** [comment]
Fixed
